### ISSUE TITLE
Why does updateFrame only fetch at most one byte per invocation?

### ISSUE THREAD

**Issue by bottlehall** [jmstriegel/Plantower_PMS7003#2]
Thank you for providing this repo. I have noticed that updateFrame only fetches, at most, one data byte from the sensor per call when, potentially, there could be more than one. I tried changing line 41 of `Planter_PMS7003.cpp` from:
`if(serial->available()) {`
to:
`while (serial->available() && bufferIndex < PMS7003_DATA_SIZE) {`
It all works well in my project but I was wondering if I have missed something and there is a reason why it is thus limited?

**Comment by jmstriegel** [comment]
Your recommendation looks good to me. If you've tested it, go ahead and submit a pull request.

**Comment by bottlehall** [comment]
Thank you, I've created a PR for this.

**Comment by jmstriegel** [comment]
Merged - thanks!
